services:
  frontend:
    build: .
    container_name: gestao-contatos-frontend
    restart: always
    ports:
      - 7773:5173
    networks:
      - gestao-contatos

networks:
  gestao-contatos:
    external: true